name: Music We Make Hot 40
favicon: null
layout_spectrum: 0.27736337715759873
typography_spectrum: 0.8400264834053814
title: The very best songs coming to you every week from Music We Make
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#acbbcc'
    - '#c8623f'
    - '#3a6785'
    - '#6d311a'
    - '#202123'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
