name: Music We Make Hot 40
favicon: null
layout_spectrum: 0.27736337715759873
typography_spectrum: 0.8400264834053814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4853931611869484
  lightness: 0.6700113685801625
  saturation: 0.20052322442643344
  rhythmicContrast: 0.48325545131228864
purpose: []
